In [2]:
import pandas as pd 
import torch 
import numpy as np 
import matplotlib.pyplot as plt 

C:\Users\agnes\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\agnes\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (


In [3]:
## scalar 
scalar = torch.tensor(7)

In [4]:
scalar.ndim

0

In [5]:
## get tensor back as python int 
scalar.item()

7

In [6]:
## vector -- magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
## MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
## TENSOR
TENSOR= torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

## random tensors
- way many neural networks learn 
- they start with tensors will full of random numbers and then adjust those random numbers to better represent the data

In [13]:
# random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4696, 0.7450, 0.8713, 0.6813],
        [0.0482, 0.3434, 0.0579, 0.5200],
        [0.5804, 0.7153, 0.5376, 0.2024]])

In [14]:
random_image_size_tensor= torch.rand(size=(224,224,3)) ## height, width, color channels


## Zeros and ones

In [15]:
## create a tensor of all zeros 
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
## create a tensor of all 1s 
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## create a range of tensors and tensors-like

In [17]:
torch.arange(0,10) ## not range anymore 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
torch.__version__

'2.1.2+cpu'

In [19]:
one_to_ten=torch.arange(start=0, end =1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [20]:
## creating tensors like
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## tensor datatypes
## 32 bit = computer stores as 32 bit , single precision
## tensor data types is one of the 3 big errors youll run into with Pytorch
### 1 ) tensors not right datatype 
### 2) tensors not right shape 
### 3) tensors  not on right device

In [25]:
# float 32 tensor 
 
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what datatype is tensor
                               device= "cpu", #cuda, cpu 
                               requires_grad=False) # track gradients

In [24]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
result =float_16_tensor * float_32_tensor

In [29]:
result

tensor([ 9., 36., 81.])

In [30]:
type(result)

torch.Tensor

In [31]:
int_32_tensor= torch.tensor([3,6,9], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor ### cant do Long 

tensor([ 9., 36., 81.])

## getting information from tensors 
### - dtype - can use 'tensor.dtype'
### - shape - can use 'tensor.shape'
### - device - can use 'tensor.device'

In [33]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4268, 0.2012, 0.8066, 0.0308],
        [0.3581, 0.5646, 0.8653, 0.4060],
        [0.5325, 0.8245, 0.1956, 0.8298]])

In [37]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")



tensor([[0.4268, 0.2012, 0.8066, 0.0308],
        [0.3581, 0.5646, 0.8653, 0.4060],
        [0.5325, 0.8245, 0.1956, 0.8298]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# manipulating tensors (tensor operations)
- addition
- subtraction
- multiplication 
- division
- matrix multiplication

In [38]:
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [40]:
tensor= tensor * 10

In [41]:
tensor

tensor([10, 20, 30])

In [42]:
tensor-10

tensor([ 0, 10, 20])

In [43]:
torch.mul(tensor,10)

tensor([100, 200, 300])

## matrix multiplication
### - element wise 
### - matrix multiplication
## 2 main rules that performing matrix multiplication needs to satisfy 
## 1) inner dimensions need to match 
## 2) resulting matrix has the shape of the outer dimensions

In [44]:
print(tensor, "*", tensor)


tensor([10, 20, 30]) * tensor([10, 20, 30])


In [45]:
print(f"Equals : {tensor * tensor}")

Equals : tensor([100, 400, 900])


In [46]:
# matrix mult
torch.matmul(tensor, tensor)

tensor(1400)

In [47]:
value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)


In [48]:
torch.matmul(tensor, tensor)

tensor(1400)

In [52]:
## shape errors very common 
tensor_A= torch.tensor([[1,2],[3,4],[5,6]])
tensor_B= torch.tensor([[7,10],[8,11],[9,12]])
res=torch.matmul(tensor_A ,tensor_B)
res

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## do transpose for shape issues

In [53]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [54]:
torch.matmul(tensor_A ,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## finding min, max,mean , sum = tensor aggregation

In [56]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [59]:
# mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [61]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding positional min and max

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
x.argmin()

tensor(0)

In [64]:
x[0]

tensor(0)

In [66]:
## find position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [68]:
x.argmin()

tensor(0)

In [69]:
x[0]

tensor(0)

### reshaping, stackng , squeezing and unsqueezing tensors 
- reshaping : reshapes an input tensor to a defined shape 
- view: return a view of an input tensor of certain shape but keep same memory as original tensor 
- stacking: combine multiple tensors on top of each other (vstack) or side by side (h stack)
- squeeze: removes all `1` dimensions from a tensor 
- unsqueee: add a `1` dimension to a target tensor 
- permute: return a view of the input with dimensions permuted (swapped) in a certain way

In [70]:
y=torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
y_reshaped= y.reshape(1,9)
y_reshaped, y_reshaped.shape
## reshape has to be original dimension

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
## change the view 
z= y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
## changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0]=5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [79]:
## stack tensors on top
y_stacked= torch.stack([y,y,y,y], dim=1)
y_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

### torch.squeeze() - remove all single dimensions from a target tensor

In [81]:
a= torch.zeros(2,1,2,1,2)
a.size()


torch.Size([2, 1, 2, 1, 2])

In [82]:
b=torch.squeeze(a)
b.size()

torch.Size([2, 2, 2])

In [83]:
b=torch.squeeze(a,0)
b.size()

torch.Size([2, 1, 2, 1, 2])

In [84]:
b=torch.squeeze(a,1)
b.size()

torch.Size([2, 2, 1, 2])

In [85]:
y_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
y_reshaped.squeeze().shape

torch.Size([9])

In [89]:
## torch.permute() rearranges the dimensions of a target tensor in a specified order 
d = torch.randn(2,3,5)
d.size()


torch.Size([2, 3, 5])

In [90]:
torch.permute(d,(2,0,1)).size()

torch.Size([5, 2, 3])

In [94]:
## permute orignal tensor to rearrange axis (or dim)
x_original = torch.rand(size=(224, 224,3)) # height, width, colour_channels
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## indexing (selecting data from tensors)
### indexing pytorch is similar to indexing with numpy 

In [95]:
s = torch.arange(1,10).reshape(1,3,3)
s, s.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [96]:
s[0][0]

tensor([1, 2, 3])

In [97]:
# index on most inner bracket (last dimension)
s[0][0][0]

tensor(1)

In [98]:
# can use ':' to select all of a target dimension
s[:,:,1]

tensor([[2, 5, 8]])

In [99]:
## get all values of the 0 dimension but only the  1 index value of 1st and 2nd dimensions 
s[:,1,1]

tensor([5])

In [100]:
## get index 0 of 0th and 1st dimension and all values of 2nd dimensions 
s[0,0,:]

tensor([1, 2, 3])

In [101]:
# index on x to return 9
print(s[0][0][2])

## index on s to return 3,6,9
print(s[:,:,2])

tensor(3)
tensor([[3, 6, 9]])


# pytorch tensors and numpy 
## data in numpy , want in pytorch tensor --> `torch.from_numpy(ndarray)`
## pytorch tensor , to numpy --> `torch.Tensor.numpy()`


In [102]:
array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [103]:
array = array +1 
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [104]:
tens = torch.ones(7)
numpy_tensor= tens.numpy()
tens, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [105]:
numpy_tensor.dtype

dtype('float32')

# reproducibility : trying to take random out of random
### how a neural network learns:
` start with random numbers --> tensor operations --> update random numbers to try and make them better representations of the data --> again --> again --> again `
### to reduce the randomness in neural networks & pytorch comes the concept of a  **random seed ** 

In [107]:
random_tensor_A= torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4776, 0.0969, 0.9362, 0.9209],
        [0.1853, 0.6354, 0.3843, 0.9065],
        [0.7939, 0.2276, 0.1341, 0.3922]])
tensor([[0.3625, 0.7286, 0.7809, 0.5490],
        [0.8065, 0.3577, 0.8937, 0.9425],
        [0.3194, 0.3580, 0.2503, 0.1076]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [108]:
## random but reprorducible tensors 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_D= torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C== random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running tensors and pytorch objects on the GPUs (& faster computations)
- GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch hardware working behind the scenes 


In [109]:
!nvidia-smi

Mon Jun 23 13:36:07 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.80                 Driver Version: 546.80       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   56C    P5              25W /  40W |      0MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [110]:
## check for GPU access with pytorch

torch.cuda.is_available()

False

In [111]:
# set up device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [114]:
tensor = torch.tensor([1,2,3], device="cpu")

In [116]:
## move tensor to gpu if available 
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [117]:
# if tensor is on GPU , cant transform it to numpy
tensor_on_gpu.numpy()

array([1, 2, 3], dtype=int64)

### exercises